In [1]:
import cv2
import numpy

In [2]:
img = cv2.imread("mountains.jpg")

In [7]:
kernel = numpy.array([[1,1,1], [0,0,0], [-1,-1,-1]])
print(kernel)
newimg = cv2.filter2D(img, -1, kernel)
cv2.imshow("Edge Detection", numpy.hstack((img,newimg)))
cv2.waitKey(0)
cv2.destroyAllWindows

[[ 1  1  1]
 [ 0  0  0]
 [-1 -1 -1]]


<function destroyAllWindows>

In [8]:
kernel = numpy.array([[-1,-1,-1], [0,0,0], [1,1,1]])
print(kernel)
newimg2 = cv2.filter2D(img, -1, kernel)
cv2.imshow("Edge Detection", numpy.hstack((newimg,newimg2)))
cv2.waitKey(0)
cv2.destroyAllWindows

[[-1 -1 -1]
 [ 0  0  0]
 [ 1  1  1]]


<function destroyAllWindows>

In [15]:
kernel = numpy.array([[0,1,0],[0,-1,0],[0,0,0]])
print(kernel)
newimg = cv2.filter2D(img, -1, kernel)
cv2.imshow("Edge Detection", numpy.hstack((img,newimg)))
cv2.waitKey(0)
cv2.destroyAllWindows

[[ 0  1  0]
 [ 0 -1  0]
 [ 0  0  0]]


<function destroyAllWindows>